# Generated by Django 5.0.1 on 2024-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_alter_plane_image_alter_plane_luggage_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='luggage_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Luggage Volume'),
        ),
    ]
