# Generated by Django 5.0.1 on 2024-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_alter_plane_luggage_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plane',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
