# Generated by Django 4.2.10 on 2024-02-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_category_slug_plane_slug_producer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='plane',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['name']},
        ),
    ]
